services:
  jerememe_server:
    build: ./server
    environment:
      NODE_ENV: ${NODE_ENV}
      CDN_PREFIX: ${CDN_PREFIX}
    image: jerememe_server
    container_name: jerememe_server
    ports:
      - 8080:8080
