name: extractor
description: Create a searchable database from video and subtitles
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  collection: ^1.19.1
  path: ^1.9.1
  sqlite3: ^2.9.3

dev_dependencies:
  lints: ^6.0.0
