name: app
description: "Meme generator app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^3.0.2
  freezed_annotation: ^3.1.0
  google_fonts: ^6.3.2
  go_router: ^16.2.5
  http: ^1.5.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.2
  video_player: ^2.10.0
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.2
  riverpod_lint: ^3.0.2

flutter:
  uses-material-design: true

  fonts:
    - family: Lithos
      fonts:
        - asset: assets/fonts/lithos.ttf
          weight: 500
